// ERRORS
export const SET_ERROR = 'SET_ERROR';

// LOADING
export const SET_LOADING = 'SET_LOADING';

// LOGIN
export const LOGOUT = 'LOGOUT';
export const CHECKED_LOGIN = 'CHECKED_LOGIN';
export const RECEIVE_USER_SESSION = 'RECEIVE_USER_SESSION';
export const SET_AVAILABLE_GROUPS = 'SET_AVAILABLE_GROUPS';

// INPUT
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const UPDATE_INPUTS = 'UPDATE_INPUTS';

// FACILITATOR
export const SET_SIM_SETTINGS = 'SET_SIM_SETTINGS';
export const IMPERSONATE_USER = 'IMPERSONATE_USER';
export const CLEAR_IMPERSONATION = 'CLEAR_IMPERSONATION';
